### PR TITLE
fixed the navbar of talking therapy page 

### PR DESCRIPTION
**Pull request by Vanshiii203**
issue #397 

Screenshot (394)

### CODE REVIEW

**Review by Susmita-Dey — CHANGES_REQUESTED** [review]
Pull the recent changes in the website

**Comment by Vanshiii203** [comment]
> Pull the recent changes in the website

pulled

**Comment by Susmita-Dey** [comment]
@Vanshiii203 pull once again

**Review by Susmita-Dey — APPROVED** [review]
LGTM

**Pull request merged**
