### PR TITLE
updated login/signup page

### PR DESCRIPTION
**Pull request by undextered**

### CODE REVIEW

**Comment by Susmita-Dey** [comment]
@undextered Issue no?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by undextered** [comment]
> @undextered Issue no?
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** What do you mean?

**Comment by undextered** [comment]
What do you mean?????

**Comment by Susmita-Dey** [comment]
@undextered Have you been assigned any issue for creating this PR?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by undextered** [comment]
#220 it is

**Comment by undextered** [comment]
> @undextered Have you been assigned any issue for creating this PR?
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** question I have a question

#220

**Comment by undextered** [comment]
> Awesome job.
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** trophy This code is awesome  |  **Tags:** Efficient

Thank you so much

**Pull request merged**
