### PR TITLE
Made the footer of therapy pages similar to Home page

### PR DESCRIPTION
**Pull request by Vanshiii203**
Made the footer of all therapy pages similar to Home page
issue #344 

https://user-images.githubusercontent.com/94471189/189473966-0e6abd76-27a8-4c3c-b03b-a8c4b5a34071.mp4

### CODE REVIEW

**Review by imaaquibali — APPROVED** [review]

**Comment by imaaquibali** [comment]
@Susmita-Dey Can you check the deployment its not working?

**Review by Susmita-Dey — CHANGES_REQUESTED** [review]
The font of other therapy pages and Yoga therapy page look different. 

For All therapies:
image

For Yoga therapy:
image

Kindly fix it.

**Comment by Susmita-Dey** [comment]
> @Susmita-Dey Can you check the deployment its not working?

It's working properly

**Comment by Vanshiii203** [comment]
> The font of other therapy pages and Yoga therapy page look different.
> 
> For All therapies: image
> 
> For Yoga therapy: image
> 
> Kindly fix it.

Fixed it. Please review

**Review by Susmita-Dey — APPROVED** [review]
LGTM. Good job. 

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Pull request merged**
