### PR TITLE
Updated the Contact Page under issue no. 72 [SSOC]

### PR DESCRIPTION
**Pull request by ShivanshAr97**
Contact page has been improved.

image

### CODE REVIEW

**Comment by SachinMittal1766** [comment]
Currently, all the field are accepting blank space as entry. 
Modify code to resolve this issue

**Comment by ShivanshAr97** [comment]
Issue has been resolved.

image

**Comment by myhacktech** [comment]
> Issue has been resolved.
> 
> image

great

**Comment by myhacktech** [comment]
@ShivanshAr97 resolve conflicts ,then i'll merge it

**Comment by Vanshiii203** [comment]
@SachinMittal1766 @myhacktech The issue was already assign to me under issue#37 and I have fixed it : https://github.com/Susmita-Dey/Sukoon/pull/90

**Comment by ShivanshAr97** [comment]
> @ShivanshAr97 resolve conflicts ,then i'll merge it

Done 👍

**Comment by ShivanshAr97** [comment]
> @SachinMittal1766 @myhacktech The issue was already assign to me under issue #37 and I have fixed it : #90

image

==>

image

Did you copy my code or something like that??

**Comment by myhacktech** [comment]
> @SachinMittal1766 @myhacktech The issue was already assign to me under issue #37 and I have fixed it : #90

no prblm,your PR is merged and points will be given to you,this Pr will be considered as an advancement to your work

**Comment by myhacktech** [comment]
> > @SachinMittal1766 @myhacktech The issue was already assign to me under issue #37 and I have fixed it : #90
> 
> no prblm,your PR is merged and points will be given to you,this Pr will be considered as an advancement to your work

@Vanshiii203

**Review by SachinMittal1766 — APPROVED** [review]
Looks Good

**Pull request merged**
