### PR TITLE
Added a new button show/hide password

### PR DESCRIPTION
**Pull request by NageshMandal**
https://user-images.githubusercontent.com/106006006/191922670-de7af744-5c1e-43d4-b583-a23376907ba9.mp4

### CODE REVIEW

**Comment by myhacktech** [comment]
issue no. ?

**Comment by NageshMandal** [comment]
#426

**Review by myhacktech — APPROVED** [review]
lgtm @Susmita-Dey

**Comment by Susmita-Dey** [comment]
@NageshMandal pull recent changes

**Comment by Susmita-Dey** [comment]
@NageshMandal pull recent changes and fix the merge conflicts

**Comment by NageshMandal** [comment]
Could you please explane what i have to do i couldn't understand the problem

**Comment by myhacktech** [comment]
> Could you please explane what i have to do i couldn't understand the problem

Go to ur forked repo of sukoon and pull recent changes that have been made to to project,if u have doubt dm me in discord

**Pull request closed without merging**
