### PR TITLE
Improved the width of Image & visibility of points in Yoga Therapy Page

### PR DESCRIPTION
**Pull request by MohitNamdev22**
Issue #283 
I've improved the width of the image & and the visibility of text present under the benefits of yoga on the yoga therapy page.

image

### CODE REVIEW

**Comment by Susmita-Dey** [comment]
@MohitNamdev22 Fix the merge conflicts.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

**Review by Susmita-Dey — APPROVED** [review]
LGTM.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Comment by MohitNamdev22** [comment]
Resolved the conflicts

**Review by Susmita-Dey — APPROVED** [review]
LGTM.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Pull request merged**
