### PR TITLE
Improved the Contact-Us page& submit button

### PR DESCRIPTION
**Pull request by Vanshiii203**
issue #281 

https://user-images.githubusercontent.com/94471189/185907828-7fc64181-2fa0-4e91-9c1b-144d71fea9d5.mp4

### CODE REVIEW

**Review by myhacktech — APPROVED** [review]

**Review by Susmita-Dey — CHANGES_REQUESTED** [review]
Background is too pinkish and doen't looks professional. Can you change it?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by Vanshiii203** [comment]
> Background is too pinkish and doen't looks professional. Can you change it?
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** 🛠️ This code needs a fix

Sure!

**Comment by ShivanshAr97** [comment]
https://github.com/Susmita-Dey/Sukoon/pull/90 🙂

**Comment by Susmita-Dey** [comment]
@Vanshiii203 Are you doing this for the second time?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by Vanshiii203** [comment]
> @Vanshiii203 Are you doing this for the second time?
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** ❓ I have a question

Yes, after my PR #90 was merged, there was another PR that was merged for this page(currently present) which did not have proper effects and transitions for the button.

**Comment by Susmita-Dey** [comment]
@Vanshiii203 oh ok

**Comment by Vanshiii203** [comment]
@Susmita-Dey 
Screenshot (348)

**Review by Susmita-Dey — APPROVED** [review]
LGTM.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant

**Comment by Vanshiii203** [comment]
@Susmita-Dey 
I am not able to see the changes on the website, but on my system they work fine. Is this happening because of the broken code?
On Website-
Screenshot (351)

On my system-
Screenshot (352)

**Pull request merged**
