### PR TITLE
Alignment

### PR DESCRIPTION
**Pull request by ASP124**
Solved the issue of #623

### CODE REVIEW

**Comment by Susmita-Dey** [comment]
Hey @ASP124 Kindly update your branch

**Comment by Kiran1689** [comment]
Hey @Susmita-Dey , Can I submit a new PR for this? The login page issue still persists.

**Comment by Susmita-Dey** [comment]
> Hey @Susmita-Dey , Can I submit a new PR for this? The login page issue still persists.

Then close this PR and submit a new one

**Comment by Kiran1689** [comment]
> > Hey @Susmita-Dey , Can I submit a new PR for this? The login page issue still persists.
> 
> Then close this PR and submit a new one

You can close this PR, new PR already merged.

**Comment by Kiran1689** [comment]
@Susmita-Dey #628

**Pull request closed without merging**
