### PR TITLE
Made email link responsive

### PR DESCRIPTION
**Pull request by keerthana054**

### CODE REVIEW

**Comment by Susmita-Dey** [comment]
@keerthana054 Add issue number and screenshot of your changes. Also, complete both the tasks in the same PR because your issue contains 2 taska.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by imaaquibali** [comment]
@keerthana054 Don't upload the filles use git commands to upload. If you faced any problem pls let me know.  I'm happy to happy to help you 😃

**Review by imaaquibali — APPROVED** [review]

**Comment by imaaquibali** [comment]
@keerthana054 Please solve the conflict!

**Review by imaaquibali — CHANGES_REQUESTED** [review]
Solve the conflict. If you faced any problem ping me on discord!

**Comment by Susmita-Dey** [comment]
@keerthana054 It's been so many days. Kindly fix it ASAP

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Review by AliReza1083 — COMMENTED** [review]
I reviewed your codes, and I didn't find any problem, It was nice and clean.
Wish you all the best.

**Comment by keerthana054** [comment]
> I reviewed your codes, and I didn't find any problem, It was nice and clean. Wish you all the best
Thank you!

**Comment by Susmita-Dey** [comment]
@keerthana054 Any updates on this PR?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by keerthana054** [comment]
> @keerthana054 Any updates on this PR?
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** ❓ I have a question

I couldn't change the social media icons mam!

**Comment by Susmita-Dey** [comment]
@keerthana054 Shall I close this PR?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by keerthana054** [comment]
> @keerthana054 Shall I close this PR?
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** ❓ I have a question

Yes mam! Thank you

**Pull request closed without merging**
