### PR TITLE
Our services

### PR DESCRIPTION
**Pull request by con-artist**
image
this is my PR for issue https://github.com/Susmita-Dey/Sukoon/issues/114

Please merge :)

### CODE REVIEW

**Comment by myhacktech** [comment]
> image this is my PR for issue #114
> 
> Please merge :)

https://sukoon-stress-free.netlify.app/ but this is already functioning on live website

**Comment by con-artist** [comment]
@myhacktech  bro check the original sukoon website  https://sukoon-stress-free.netlify.app/ . I have improved the ui of our services section . So please merge this .

**Comment by myhacktech** [comment]
> @myhacktech bro check the original sukoon website https://sukoon-stress-free.netlify.app/ . I have improved the ui of our services section . So please merge this .

i can see that ,u worked on responsiveness

**Review by Susmita-Dey — COMMENTED** [review]
Hey @con-artist I can see here you changed the number of cards from 3 to 2 and it contains huge gap between them and also not a good UI experience from a user point of view.  Also, you have added `CONTRIBUTING.md` file in your PR which already exists. 

Talking about responsiveness it's not responsive and the responsive issue is assigned to someone else. Also, you didn't mentioned about responsive in your issue.

Sorry I can't merge your PR. 


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by con-artist** [comment]
@Susmita-Dey if you check this link https://deploy-preview-126--sukoon-stress-free.netlify.app/ You will see there are 3 cards upto 950px. Also Not sure why you say its not responsive but for me it seems to be responsive. And I have also changed the UI of the cards and as for the contribution.md file ,not sure how that got added since I didn't really create it, probably something happened when I did "git pull upstream..". Anyways Can you please check again and see if you are not zoomed in or something.

image
image

**Comment by Susmita-Dey** [comment]
> @Susmita-Dey if you check this link https://deploy-preview-126--sukoon-stress-free.netlify.app/ You will see there are 3 cards upto 950px. Also Not sure why you say its not responsive but for me it seems to be responsive. And I have also changed the UI of the cards and as for the contribution.md file ,not sure how that got added since I didn't really create it, probably something happened when I did "git pull upstream..". Anyways Can you please check again and see if you are not zoomed in or something.
> 
> image image

It's showing me 2 cards. What shall I do?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by con-artist** [comment]
Could you try zooming out to 90 or 100%

**Comment by Susmita-Dey** [comment]
> Could you try zooming out to 90 or 100% Or you could inspect and check for different sizes

I have checked from every aspect.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Inefficient

**Comment by con-artist** [comment]
could you send a screenshot

**Pull request closed without merging**
