### PR TITLE
Fixed #488: Updated 'contributing.md'.

### LINKED ISSUE #488: Making contributing.md more readable
What:
Every point listed should start from a new line to make it more readable.

Image:
image

### PR DESCRIPTION
**Pull request by bhattabhi013**
What:
Fixes issue #488.

Image:
image

### CODE REVIEW

**Review by myhacktech — APPROVED** [review]

**Comment by myhacktech** [comment]
mention link in which u hv made changes?

**Comment by bhattabhi013** [comment]
Changes are made in 'contributing.md' file.


image

**Comment by Stk-79** [comment]
I can work on this more, Please assign me. @Susmita-Dey  @myhacktech

**Comment by Susmita-Dey** [comment]
@Stk-79 It's a PR not any issue.

**Review by Susmita-Dey — APPROVED** [review]
LGTM

**Comment by Stk-79** [comment]
> @Stk-79 It's a PR not any issue.

Yes Ma'am ,But some links inside it are not working properly as created which can be made perfect along with other small changes too. Should I raise another issue to modify it ? @Susmita-Dey

**Pull request merged**
