### PR TITLE
issue #81

### PR DESCRIPTION
**Pull request by 09khu**
Added login and signup form file.
Issue link :- https://github.com/Susmita-Dey/Sukoon/issues/81
image

### CODE REVIEW

**Comment by myhacktech** [comment]
@09khu transition is not smooth,try to do it

**Review by siddhi-244 — APPROVED** [review]
LGTM

**Review by Susmita-Dey — CHANGES_REQUESTED** [review]
Can you create a separate javascript file for the javascript code and link it to the html file?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question&nbsp; | &nbsp;**Tags:** Efficient

**Comment by 09khu** [comment]
> Can you create a separate javascript file for the javascript code and link it to the html file?
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** ❓ I have a question  |  **Tags:** Efficient

Okay 👍

**Review by Susmita-Dey — APPROVED** [review]
LGTM. Merging to main.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Pull request merged**
