### PR TITLE
Added the hover animation for the social links in the footer section

### PR DESCRIPTION
**Pull request by RitikRG**
I have added the scaling animation for the footer section's social links.
The icons scale to 1.4 with a transition duration of 250ms and each of them have a specific color as per the  company's official logo.

I will unlist this website once you check it out

[Check how it looks](https://issue578.netlify.app/)

### CODE REVIEW

**Review by Susmita-Dey — COMMENTED** [review]
The github one doesn't look good. What can be done is either remove the colors or change the github logo color

**Comment by RitikRG** [comment]
@Susmita-Dey can you suggest a color for the github one

**Comment by Susmita-Dey** [comment]
> @Susmita-Dey can you suggest a color for the github one

Try out colors or better keep the previous color

**Comment by RitikRG** [comment]
@Susmita-Dey 
I have changed the github logo hover animation 
Can you please check it out [here](https://issue578.netlify.app/) if you feel it's good only then I will change for rest of the files

and also extremely sorry if I am being annoying, it's just that it's my first time contributing so I just don't want to mess it up

**Review by Susmita-Dey — APPROVED** [review]
Looks great

**Comment by Susmita-Dey** [comment]
> @Susmita-Dey I have changed the github logo hover animation Can you please check it out [here](https://issue578.netlify.app/) if you feel it's good only then I will change for rest of the files
> 
> and also extremely sorry if I am being annoying, it's just that it's my first time contributing so I just don't want to mess it up

nvm. We together learn and grow. These things often happen when you contribute to open source projects.

**Comment by RitikRG** [comment]
@Susmita-Dey 
Thanks I will complete the changes now

**Comment by RitikRG** [comment]
@Susmita-Dey 
I have completed the changes for all the files
Thank you very much for letting me work on your project and making my first contribution experience so smooth

**Comment by Susmita-Dey** [comment]
@RitikRG Share your achievement of getting your first PR merged with the repo link at your socials.

**Comment by RitikRG** [comment]
@Susmita-Dey Thank you very much

**Pull request merged**
