### PR TITLE
Fix Issue #361 Improving the design of the mobile layout navbar menu on home page

### PR DESCRIPTION
**Pull request by SahilDahekar**
- Issue no. #361 
- Improved the animation of the menu slide in.
- Removed the home link tag from navbar on home page.
- Added custom svg for hamburger.
- Added toggle function to it with close svg.
- Added hover function to hamburger as well.
- Improved menu css (background color, hover , hover transition).

Screenshot 2022-09-14 191942
Screenshot 2022-09-14 192022

### CODE REVIEW

**Review by Susmita-Dey — APPROVED** [review]
LGTM

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Review by myhacktech — APPROVED** [review]

**Review by Susmita-Dey — CHANGES_REQUESTED** [review]
Pull the recent changes in the website

**Comment by SahilDahekar** [comment]
> Pull the recent changes in the website

Done

**Review by Susmita-Dey — APPROVED** [review]
LGTM

**Pull request merged**
