### PR TITLE
Improved fonts readablity in title,paragraph and for the button and made the videos section responsive in yoga therapy page 

### PR DESCRIPTION
**Pull request by popcandy1x**
Changed the font ui of title and paragraph, changed the 'more assans' button UI and made the videos section responsive
Issue:https://github.com/Susmita-Dey/Sukoon/issues/267
New Pull Request created with respect to the previous pull request:https://github.com/Susmita-Dey/Sukoon/pull/306
Website on which I worked:https://sukoon-stress-free.netlify.app/html/yogatherapy.html

### CODE REVIEW

**Review by Susmita-Dey — APPROVED** [review]
LGTM

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Review by Susmita-Dey — CHANGES_REQUESTED** [review]
Fix the footer. Your PR have destroyed the footer.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

**Comment by popcandy1x** [comment]
> Fix the footer. Your PR have destroyed the footer.
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** 🛠️ This code needs a fix  |  **Tags:** Not reusable

Ok

**Comment by popcandy1x** [comment]
> Fix the footer. Your PR have destroyed the footer.
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** 🛠️ This code needs a fix  |  **Tags:** Not reusable

Fixed the footer CSS hover effects as per the recent commits in the website

**Review by Susmita-Dey — CHANGES_REQUESTED** [review]
Fix merge conflicts ASAP @popcandy1x

**Comment by popcandy1x** [comment]
The above☝️ changes had already been done by someone in the website,so closing my pull request.

**Pull request closed without merging**
