### PR TITLE
Header section UI fixed

### PR DESCRIPTION
**Pull request by con-artist**
This is the pull request for issue #176

Earlier:
image
Now
image

### CODE REVIEW

**Comment by myhacktech** [comment]
Screenshot (671)
work on this part also

**Comment by Susmita-Dey** [comment]
@con-artist Site is fully responsive. What changes are you making?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by con-artist** [comment]
I made this PR 5 days ago. 
image

I have fixed this issue

**Comment by con-artist** [comment]
Can you merge this? The issue is resolved

**Review by Susmita-Dey — APPROVED** [review]
LGTM. Thanks for fixing it.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Pull request merged**
