### PR TITLE
Add Website link in Readme.

### PR DESCRIPTION
**Pull request by rakshitgondwal**
Changes made-
- Added the live web hosting link for the website in the readme.

### CODE REVIEW

**Comment by Susmita-Dey** [comment]
@rakshitgondwal Issue no?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by rakshitgondwal** [comment]
> @rakshitgondwal Issue no?
> 
> __
> [sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question
> 

nope. no issue.

**Comment by Susmita-Dey** [comment]
I can't merge like this

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by rakshitgondwal** [comment]
closes #254

**Comment by rakshitgondwal** [comment]
@Susmita-Dey is it alright now?

**Comment by Susmita-Dey** [comment]
> @Susmita-Dey is it alright now?

yes

**Review by Susmita-Dey — APPROVED** [review]
LGTM.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Pull request merged**
