### PR TITLE
Update audioTherapy.html

### PR DESCRIPTION
**Pull request by Kritika0035**
Signed-off-by: Kritika0035 <92821377+Kritika0035@users.noreply.github.com>

### CODE REVIEW

**Comment by Kritika0035** [comment]
this is for the text alignment of audiobooks.

**Comment by Susmita-Dey** [comment]
@Kritika0035 issue no?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Review by Susmita-Dey — APPROVED** [review]
LGTM

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Comment by Kritika0035** [comment]
issue no. 245 only.....previous was in css h nd this one is in html.

**Comment by Susmita-Dey** [comment]
@Kritika0035 you should have done things in a single PR only then

**Comment by Kritika0035** [comment]
sorry for that....it was the first time so I did one at a time... but will remember this now onwards.

**Pull request merged**
