### PR TITLE
Compressed images to 200KB 

### LINKED ISSUE #507: App size is too bulky because of images folder which costs 50mb
Because of that, website is taking too much time to load, so I want to compress the images using  https://imagecompressor.com/

### PR DESCRIPTION
**Pull request by BhavyaJain711**
closes #507 
Compressed images to maximum size of 200KB and changed img src extension from jpeg to jpg in index.html

### CODE REVIEW

**Comment by BhavyaJain711** [comment]
Also please add the HacktoberFest label

**Comment by Susmita-Dey** [comment]
@BhavyaJain711 This repo is not under hacktoberfest

**Review by Susmita-Dey — CHANGES_REQUESTED** [review]
Kindly follow this [doc](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/keeping-your-pull-request-in-sync-with-the-base-branch) and update your branch. I'll review and merge after that.

**Review by Susmita-Dey — APPROVED** [review]
LGTM. Thanks :)

**Comment by Susmita-Dey** [comment]
> Also please add the HacktoberFest label

Done

**Pull request merged**
