### PR TITLE
Initializing animate on scroll AOS in the app  

### PR DESCRIPTION
**Pull request by itsmdasifraza**
fixes issue #450 <https://michalsnik.github.io/aos/>

### CODE REVIEW

**Comment by itsmdasifraza** [comment]
Working on reading therapy animation AOS

**Comment by itsmdasifraza** [comment]
working on talking therapy

**Comment by itsmdasifraza** [comment]
working on yoga therapy

**Comment by itsmdasifraza** [comment]
Checkout 5 working AOS animated service pages
1. <https://deploy-preview-478--sukoon-stress-free.netlify.app/html/audiotherapy>
2. <https://deploy-preview-478--sukoon-stress-free.netlify.app/html/readingtherapy>
3. <https://deploy-preview-478--sukoon-stress-free.netlify.app/html/yogatherapy>
4. <https://deploy-preview-478--sukoon-stress-free.netlify.app/html/talkingtherapy>
5. <https://deploy-preview-478--sukoon-stress-free.netlify.app/html/laughtherapy>

**Review by myhacktech — APPROVED** [review]
lgtm @Susmita-Dey

**Review by Susmita-Dey — APPROVED** [review]
Great job

**Pull request merged**
