### PR TITLE
Added scrolling feature to all Therapies

### PR DESCRIPTION
**Pull request by AnshuPathak-88825**

### CODE REVIEW

**Comment by AnshuPathak-88825** [comment]
Created pr of issue #186

**Comment by AnshuPathak-88825** [comment]
@Susmita-Dey pls check and merge it into the main repo

**Comment by Susmita-Dey** [comment]
@AnshuPathak-88825 First fix the merge conflicts.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

**Comment by AnshuPathak-88825** [comment]
I've fixed the merge conflicts pls merge it @Susmita-Dey 

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by Susmita-Dey** [comment]
@AnshuPathak-88825 Merge conflict again. Fix it.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

**Comment by AnshuPathak-88825** [comment]
@Susmita-Dey all conflict removed 

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Review by Susmita-Dey — COMMENTED** [review]
@AnshuPathak-88825 I can't see any changes in the deploy preview. Change the `class=".smooth-scroll"` to `class="smooth-scroll"` in the pages and before doing that show me the ss of your changes(**localhost** preview)

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by AnshuPathak-88825** [comment]
Screenshot from 2022-08-25 16-20-39
Added smooth scroll.js file 
I think someone already made this feature 
so can I close this issue  

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by Susmita-Dey** [comment]
@AnshuPathak-88825 No, it's not made by anyone. Show me the ss of localhost that the changes you have made here in this PR.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by AnshuPathak-88825** [comment]
Screenshot from 2022-08-25 16-37-27
Screenshot from 2022-08-25 16-37-34
Screenshot from 2022-08-25 16-37-42

Screenshot from 2022-08-25 16-37-56

These are all screenshots

**Comment by Susmita-Dey** [comment]
@AnshuPathak-88825 Not this one. Haven't you cloned the repo?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by AnshuPathak-88825** [comment]
No I've cloned it

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by Susmita-Dey** [comment]
@AnshuPathak-88825 I'm not getting what you wanna say.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by Susmita-Dey** [comment]
@AnshuPathak-88825 Any updates?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by AnshuPathak-88825** [comment]
Can I make new pr for this issue ?

**Comment by Susmita-Dey** [comment]
> Can I make new pr for this issue ?

Yes do it

**Comment by AnshuPathak-88825** [comment]
@Susmita-Dey this is issue is closed should I raise new issue or will you open this for new PR

**Comment by Susmita-Dey** [comment]
@AnshuPathak-88825 Create a new PR

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by AnshuPathak-88825** [comment]
Made pr #340 Should I add email for getting score

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Pull request closed without merging**
