### PR TITLE
added videos to laughing therapy page

### PR DESCRIPTION
**Pull request by Vanshiii203**
issue #383 

https://user-images.githubusercontent.com/94471189/189647436-b0edefa7-5902-4389-9c0a-0e89f9f142ce.mp4

### CODE REVIEW

**Comment by Vanshiii203** [comment]
> issue #383
@Susmita-Dey Should I include one more video to maintain consistency?

**Comment by Susmita-Dey** [comment]
@Vanshiii203 Yes you can

**Review by Susmita-Dey — CHANGES_REQUESTED** [review]
Pull the recently merged changes.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by Vanshiii203** [comment]
@Susmita-Dey  I've pulled the latest code.

**Review by Susmita-Dey — APPROVED** [review]
LGTM. Great job

**Pull request merged**
