### PR TITLE
Fix the "X" sign on Talking Therapy page

### PR DESCRIPTION
**Pull request by MohitNamdev22**
Issue #336 
I've changed the display property of icon " X ".
image

### CODE REVIEW

**Comment by MohitNamdev22** [comment]
Please have a look @Susmita-Dey

**Review by Susmita-Dey — COMMENTED** [review]
You have removed the 'x' that's okay but why there no hamburger for mobile screens.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by Susmita-Dey** [comment]
Oh god, it's my mistake. there's no such things added there

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Review by Susmita-Dey — APPROVED** [review]
LGTM

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Pull request merged**
