### PR TITLE
Created Spirituality Page 

### PR DESCRIPTION
**Pull request by MohitNamdev22**
Issue #385 
As per the above issue, I've created the spirituality page and linked it with the main page to access it.

Video - 

https://user-images.githubusercontent.com/89779447/192094957-db9c961d-ff41-4b89-87e2-17da4699f958.mp4

SSOC'22

### CODE REVIEW

**Review by Susmita-Dey — COMMENTED** [review]
@MohitNamdev22 Why there are so many files?

**Comment by MohitNamdev22** [comment]
> @MohitNamdev22 Why there are so many files?

@Susmita-Dey As per your suggestion, I've used that Teleport HQ plugin to covert figma design to HTML CSS code and that's why, they have generated those many files

**Comment by Susmita-Dey** [comment]
@MohitNamdev22 Sorry but I didn't knew that huge amount of files will be there. Can you built it using HTML if possible?

**Comment by MohitNamdev22** [comment]
> @MohitNamdev22 Sorry but I didn't knew that huge amount of files will be there. Can you built it using HTML if possible?

What's the deadline? Actually I've Midsem exams from Monday to 29th

**Comment by Susmita-Dey** [comment]
Deadline: 27th Sept

**Comment by MohitNamdev22** [comment]
> Deadline: 27th Sept

Oh Alright, I hope I'll be able to finish it by 27 🤞

**Comment by MohitNamdev22** [comment]
Hey @Susmita-Dey, Can't you merge my this PR? as I'm having Mid sem exams for the next 4 consecutive days.  And it will be very difficult to Code the whole page from scratch. And once my exams will end, no matter whether SSOC'22 ended or not I'll code and raise new PR apart from the event.

**Review by myhacktech — APPROVED** [review]
lgtm @Susmita-Dey

**Comment by Susmita-Dey** [comment]
@MohitNamdev22 Sorry but this merge won't be good. Removing the ssoc tag you can complete it by creating a new pr after ssoc ends.

**Pull request closed without merging**
