### PR TITLE
Improved fonts readablity in title,paragraph and for the button and made the videos section responsive in yoga therapy page

### PR DESCRIPTION
**Pull request by popcandy1x**
Changed the background image and font, changed the 'more assans' button UI and made the videos section responsive
Issue:https://github.com/Susmita-Dey/Sukoon/issues/267
Website on which I worked:https://sukoon-stress-free.netlify.app/html/yogatherapy.html

### CODE REVIEW

**Review by Susmita-Dey — CHANGES_REQUESTED** [review]
image
This section doesn't looks good. Also, the previous image was good. Keep the previous background. 

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by popcandy1x** [comment]
Ok👍

**Comment by popcandy1x** [comment]
> image This section doesn't looks good. Also, the previous image was good. Keep the previous background.
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** 🛠️ This code needs a fix

Ok👍

**Comment by popcandy1x** [comment]
I am closing this pr as I am not able to m

> image This section doesn't looks good. Also, the previous image was good. Keep the previous background.
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** 🛠️ This code needs a fix

I am closing this pr as I am not able to resolve the merge conflicts someone has recently made commits to the website that are causing large diffs from my code will make a new pr soon

**Pull request closed without merging**
