### PR TITLE
added animation and shadow effect to testimonial cards

### PR DESCRIPTION
**Pull request by Akayush-17**
added animation and shadow effect to testimonial cards and changed image
Screenshot 2022-09-23 221506

### CODE REVIEW

**Review by myhacktech — APPROVED** [review]
lgtm @Susmita-Dey

**Comment by Susmita-Dey** [comment]
@Akayush-17 pull recent changes in the website and ping me on discord and here

**Review by AliReza1083 — COMMENTED** [review]
I reviewed your codes, it was great.
Wish you all the best.

**Comment by Akayush-17** [comment]
> @Akayush-17 pull recent changes in the website and ping me on discord and here

@Susmita-Dey I have already made pull request.

**Review by Susmita-Dey — CHANGES_REQUESTED** [review]
Fix merge conflicts

**Comment by Susmita-Dey** [comment]
@Akayush-17 ???

**Pull request closed without merging**
