### PR TITLE
made let's explore button in same line

### PR DESCRIPTION
**Pull request by AnshuPathak-88825**

### CODE REVIEW

**Comment by AnshuPathak-88825** [comment]
PR for issue number #187

**Comment by Susmita-Dey** [comment]
@AnshuPathak-88825 fix merge conflicts

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

**Comment by AnshuPathak-88825** [comment]
@Susmita-Dey merge my PR

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by Susmita-Dey** [comment]
@AnshuPathak-88825 You have made drastic changes to the site. Check the site using the deploy preview link and there you can see the services section in completely broken form.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Inefficient, Brittle

**Comment by Susmita-Dey** [comment]
@AnshuPathak-88825 Any updates?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Pull request closed without merging**
