### PR TITLE
Title tag added (Fixes #456)

### LINKED ISSUE #456: Adding title tags on various therapy pages
I would like to add title tags on the therapy pages like **Sukoon - Yoga Therapy** on the yoga therapy page and so on on other pages as well.

Images:
image
.

### PR DESCRIPTION
**Pull request by ShivanshAr97**
Fixes #456

### CODE REVIEW

**Comment by myhacktech** [comment]
attach ss

**Comment by ShivanshAr97** [comment]
image

@myhacktech

**Comment by myhacktech** [comment]
attach screenshot

**Review by myhacktech — APPROVED** [review]

**Comment by Susmita-Dey** [comment]
@ShivanshAr97 
image
fix it. Your PR has broken things while it's okay in the original website

**Review by Susmita-Dey — APPROVED** [review]
LGTM

**Pull request merged**
