### PR TITLE
reading therapy

### PR DESCRIPTION
**Pull request by Koustavjr**
@Susmita-Dey can u please check my pr fr #52

### CODE REVIEW

**Review by Atharv-110 — COMMENTED** [review]
@Koustavjr make this section responsive.

**Review by Susmita-Dey — CHANGES_REQUESTED** [review]
The overall website looks good to me.
Can you make it responsive?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by Koustavjr** [comment]
> The overall website looks good to me. Can you make it responsive?
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** ❓ I have a question

@Susmita-Dey i have tried my best to make it responsive. can u pls check it

**Review by Susmita-Dey — CHANGES_REQUESTED** [review]
Kindly remove the .vscode folder.

**Comment by Koustavjr** [comment]
@Susmita-Dey can u please review the site, I have done my best to make it responsive, for anymore changes can u please guide me

**Review by Susmita-Dey — APPROVED** [review]
LGTM. Thanks for contributing

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Pull request merged**
