### PR TITLE
punctuation corrected  issue #321

### PR DESCRIPTION
**Pull request by 29Aastha**
image

### CODE REVIEW

**Review by Susmita-Dey — APPROVED** [review]
LGTM.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Comment by Susmita-Dey** [comment]
@29Aastha Issue no?

Note that no points will be given without issue no

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by 29Aastha** [comment]
issue number is mentioned in the commit 
issue#321

**Comment by Susmita-Dey** [comment]
> issue number is mentioned in the commit issue #321

Ok thanks

**Pull request merged**
