### PR TITLE
Pre-Loader has been added in all pages

### PR DESCRIPTION
**Pull request by Anubhavgupta14**
Pre-Loader has been added in all pages.
Spin-Preloader-1
Issue Fixed :- #423 
@Susmita-Dey @myhacktech Kindly Review it.

### CODE REVIEW

**Review by myhacktech — APPROVED** [review]

**Comment by myhacktech** [comment]
lgtm @Susmita-Dey

**Comment by myhacktech** [comment]
resolve conflicts @Anubhavgupta14

**Comment by Anubhavgupta14** [comment]
@myhacktech But there is no conflicts in this PR. As it is mentioned This Branch has no Conflicts with the base branch.

**Comment by Anubhavgupta14** [comment]
@Susmita-Dey Kindly Review it and if its ok then I request you to merge it.

**Pull request closed without merging**
