### PR TITLE
Fixed the alignment of lets explore button

### PR DESCRIPTION
**Pull request by Vanshiii203**
issue #475
Screenshot (404)

### CODE REVIEW

**Comment by Susmita-Dey** [comment]
@Vanshiii203 What have you changed?

**Comment by Vanshiii203** [comment]
> @Vanshiii203 What have you changed?

I have changed the alignment of let's explore button 
Before - 
191351973-e67065f0-6317-43db-b6b4-d5cffd701973

After -
192108998-038871bb-9007-4cab-af61-ddf37f411e44

**Comment by Susmita-Dey** [comment]
@Vanshiii203 but it's not reflected in the deploy ppreview. let me check again.

**Review by Susmita-Dey — APPROVED** [review]
LGTM

**Pull request merged**
