### PR TITLE
Update audio.css

### PR DESCRIPTION
**Pull request by Kritika0035**
Signed-off-by: Kritika0035 <92821377+Kritika0035@users.noreply.github.com>

### CODE REVIEW

**Comment by Susmita-Dey** [comment]
@Kritika0035 issue no?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by Kritika0035** [comment]
Issue number 245

**Comment by Kritika0035** [comment]
The "play now" button of audio books alignment.

**Review by Susmita-Dey — APPROVED** [review]
LGTM.

**Pull request merged**
