### PR TITLE
faq section created

### PR DESCRIPTION
**Pull request by con-artist**
image
This is my pull request to issue no #62
link : https://github.com/Susmita-Dey/Sukoon/issues/62

Please merge , thanks

### CODE REVIEW

**Review by SachinMittal1766 — COMMENTED** [review]
Add answers despite using Lorem

**Review by SachinMittal1766 — CHANGES_REQUESTED** [review]
Add answers despite using Lorem

**Comment by con-artist** [comment]
@SachinMittal1766  I have updated the answers. Please merge :)

**Review by SachinMittal1766 — APPROVED** [review]

**Comment by con-artist** [comment]
@SachinMittal1766  sorry to bother, but can you please add labels to this PR

**Pull request merged**
