### PR TITLE
 Added the carousel effect to the Testimonials section

### PR DESCRIPTION
**Pull request by vandana3869**
issue https://github.com/Susmita-Dey/Sukoon/issues/278 fixed

### CODE REVIEW

**Comment by vandana3869** [comment]
@Susmita-Dey  Please  review this PR

**Review by Susmita-Dey — CHANGES_REQUESTED** [review]
Make the following changes:
- Change the background color as per the theme of the website 
- Fix the blue border for screen sizes between **500px** to **900px** as it doesn't look good and also fix the icons for the same screen sizes as it not visible properly. 
image


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by vandana3869** [comment]
@Susmita-Dey I did the changes ... could you please review it
image

**Comment by Susmita-Dey** [comment]
@vandana3869 Your changes are not reflected in the deploy preview

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

**Comment by Susmita-Dey** [comment]
@vandana3869 Seems like you removed the scrollbar

**Comment by vandana3869** [comment]
No, it's there
image

**Comment by vandana3869** [comment]
> @vandana3869 Your changes are not reflected in the deploy preview
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** 🛠️ This code needs a fix  |  **Tags:** Not reusable

idk why this is happening ....through I updated the changes ....could you please suggest me the solution for this

**Pull request closed without merging**
