### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rakshitgondwal**
Signed-off-by: Rakshit Gondwal <98955085+rakshitgondwal@users.noreply.github.com>

Changes made-
- Updated the readme with the new screenshot of the website.

Earlier- 
Screenshot (217)

Now
Screenshot (219)
-

### CODE REVIEW

**Review by Susmita-Dey — APPROVED** [review]
LGTM. Thanks for making the changes.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Comment by Susmita-Dey** [comment]
@rakshitgondwal Issue no?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by rakshitgondwal** [comment]
> @rakshitgondwal Issue no?
> 
> __
> [sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question
> 

nope. i didn't raise any issue.

**Comment by Susmita-Dey** [comment]
@rakshitgondwal How can I merge it then?

create issues and get assigned

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question&nbsp; | &nbsp;**Tags:** Not reusable

**Comment by rakshitgondwal** [comment]
closes #255

**Comment by rakshitgondwal** [comment]
alright now? @Susmita-Dey

**Comment by Susmita-Dey** [comment]
> alright now? @Susmita-Dey

yes

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Pull request merged**
