### PR TITLE
Update footer with new logo

### PR DESCRIPTION
**Pull request by rakshitgondwal**
- Updated the footer of the website with the new logo.
- Changed the logo size from 100*100px to 140*140px.
- The 'Go stressfree' line is more visible now.

Earlier-

Screenshot (210)

Now-

Screenshot (211)

### CODE REVIEW

**Review by Atharv-110 — APPROVED** [review]
This PR is good to go for merging.
Nice work @rakshitgondwal

**Comment by rakshitgondwal** [comment]
@Atharv-110 Thanks!

**Review by Susmita-Dey — APPROVED** [review]
LGTM. Things are more visible now than earlier. Thanks.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant

**Comment by Susmita-Dey** [comment]
@rakshitgondwal What's the issue number?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by rakshitgondwal** [comment]
@Susmita-Dey Resolves issue https://github.com/Susmita-Dey/Sukoon/issues/60

**Pull request merged**
