### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by the-amazing-atharva**
Added a creative description for the website.
Beginner here !!! 
Do tell me if my method of contributing was wrong and what I could have done instead.

### CODE REVIEW

**Review by Susmita-Dey — APPROVED** [review]
LGTM. Thanks for your contribution.

**Comment by Susmita-Dey** [comment]
I'd recommend you to next time create an issue first before making PR.

**Comment by the-amazing-atharva** [comment]
Hey thanks for merging!!

Yeah definitely will create issue before merging, this actually my first time and I was not aware of normal workflow of GitHub

**Comment by Susmita-Dey** [comment]
> Hey thanks for merging!!
> 
> Yeah definitely will create issue before merging, this actually my first time and I was not aware of normal workflow of GitHub

nvm. Share this in your socials with the repository link that your first PR got merged.

**Comment by the-amazing-atharva** [comment]
Sure

**Pull request merged**
