### PR TITLE
added animated gradient

### PR DESCRIPTION
**Pull request by 29Aastha**

### CODE REVIEW

**Comment by siddhi-244** [comment]
Describe ur pr. What have you done ? Link issue

**Comment by 29Aastha** [comment]
> Describe ur pr. What have you done ? Link issue

-I have added animated gradient to the heading (h1)
- changed the font style and size of h1
- changed the colour of hover in nav bar 
- modified the style of h3 on home page

**Review by imaaquibali — APPROVED** [review]

**Review by siddhi-244 — APPROVED** [review]
LGTM

**Comment by myhacktech** [comment]
@29Aastha mention issue with#...

**Pull request merged**
