### PR TITLE
responsive about service footer section done Note: responsive nav bar…

### PR DESCRIPTION
**Pull request by Shyam3050**
Hi sushmita
i am changed about service footer section and make them responsive.
navbar responsive will added soon.
you need to fix the some internal links from member linkedin links etc
check the code.

### CODE REVIEW

**Comment by Shyam3050** [comment]
can you host on this netlify.app or any platform.

**Review by Susmita-Dey — APPROVED** [review]
LGTM! Thanks for contributing. 😊

🏆Summary: This code looks good to me.

**Comment by Susmita-Dey** [comment]
> can you host on this netlify.app or any platform.

Yes, sure!

**Comment by myhacktech** [comment]
@Shyam3050 mention issue with#?

**Comment by Susmita-Dey** [comment]
@Shyam3050 You won't get points without letting us know the issue number related to this PR.

**Pull request merged**
