### PR TITLE
Fixes issue #116

### PR DESCRIPTION
**Pull request by ShivanshAr97**
Fixes issue #116

image

Responsiveness:
image

### CODE REVIEW

**Comment by ShivanshAr97** [comment]
Please review!

**Comment by myhacktech** [comment]
> Fixes issue #116
> 
> image
> 
> Responsiveness: image

Screenshot (666)
can u work on this same way,bcz audio therapy UI has been imroved ...

**Comment by ShivanshAr97** [comment]
Sure, I saw the improved UI right now.

**Review by siddhi-244 — APPROVED** [review]

**Comment by ShivanshAr97** [comment]
Review please !

**Review by Susmita-Dey — APPROVED** [review]
LGTM. Merging to main.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Pull request merged**
