### PR TITLE
new commit

### PR DESCRIPTION
**Pull request by vaibhavsharma1234**
i have improved the responsiveness 
https://github.com/Susmita-Dey/Sukoon/issues/42

### CODE REVIEW

**Comment by vaibhavsharma1234** [comment]
Please review this

**Comment by SachinMittal1766** [comment]
Hey @vaibhavsharma1234, It is already responsive.

**Comment by vaibhavsharma1234** [comment]
There were some problem of text and other things like footer was not at centre
I fix all that

**Comment by SachinMittal1766** [comment]
Looks good
Resolve Conflicts then I will merge it

**Comment by vaibhavsharma1234** [comment]
Ok

**Comment by vaibhavsharma1234** [comment]
how do i resolve the conflicts 
previously when i write 
git pull upstream main
it shows about current changes and incoming changes 
but this time not happening 
what to do

**Comment by SachinMittal1766** [comment]
I hope this will help you. https://www.youtube.com/watch?v=JtIX3HJKwfo

**Comment by myhacktech** [comment]
> i have improved the responsiveness #42

i dont find any chages,describe it with screenshots

**Comment by myhacktech** [comment]
and resolve conflicts by pulling latest chages in repo

**Comment by vaibhavsharma1234** [comment]
images-made-clear
centered-footer
hero-section-was-extending-too-much

**Review by SachinMittal1766 — APPROVED** [review]
Good Job

**Comment by vaibhavsharma1234** [comment]
thanks 
i am glad that i can contribute 
now moving on to the next issue

**Pull request merged**
