### PR TITLE
add authentication to login page and add backend and mongodb

### PR DESCRIPTION
**Pull request by souravbhunia07**
issue #51 
add authentication to login page and add backend, add mongodb and organize the codes.

### CODE REVIEW

**Review by Susmita-Dey — COMMENTED** [review]
@souravbhunia07 Is the website running locally after you made this changes? 
Can you share a screenshot/video? 
Can you delete the .vscode file?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by souravbhunia07** [comment]
it is running locally, but you can connect it to MongoDB atlas and publish it online.
if you just clone the project you have to run this command to install all modules.
image
after that, you have to run this
image
if connection successful appear then it's running perfectly.
prerequisite for running:
1. Node and MongoDB should be installed.
if you want to host it then you can easily connect it by using Mongo atlas as database.
and i haven't deleted .vscode folder.

@Susmita-Dey

**Comment by Susmita-Dey** [comment]
@souravbhunia07 Your branch has merge conflicts and also show me the ss that the site is running locally. I wanna see the webspage

**Comment by souravbhunia07** [comment]
image
image
image
image
image
image
image

**Comment by Susmita-Dey** [comment]
It's been so many days. There are so much of merge conflicts.

**Comment by myhacktech** [comment]
@souravbhunia07 updates?

**Comment by Susmita-Dey** [comment]
Closing this as not needed

**Pull request closed without merging**
