### PR TITLE
Improving Grammatical Errors 

### PR DESCRIPTION
**Pull request by soumil1**
Improving Grammatical Errors in the readme file

### CODE REVIEW

**Comment by siddhi-244** [comment]
Have you opened a issue first ? @Susmita-Dey is this fine ?

**Comment by soumil1** [comment]
> Have you opened a issue first ? @Susmita-Dey is this fine ?

Yes, I have already created an issue and been assigned to this task; you can see it here: https://github.com/Susmita-Dey/Sukoon/issues/83#issue-1330815789

**Comment by rakshitgondwal** [comment]
Umm, I think the grammar was fine already. There is no need for a change according to me. The sentences look even more odd after the changes.

**Review by Susmita-Dey — COMMENTED** [review]
@soumil1 I agree with @rakshitgondwal  These changes are weird. Sorry I can't merge your PR.



__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Inefficient, Not reusable

**Pull request closed without merging**
