### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by AliReza1083**
The changes that I've brought:
- [x] Remove the extra Lines

```diff
- 2 or 3 lines
+ 1 line
```

### CODE REVIEW

**Comment by Susmita-Dey** [comment]
@AliReza1083 Fix the merge conflicts

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

**Comment by AliReza1083** [comment]
@Susmita-Dey 
is it fixed?

**Comment by Susmita-Dey** [comment]
> @Susmita-Dey is it fixed?

Yes

**Comment by AliReza1083** [comment]
So, should I work with that issue right now (service section)?

**Comment by Susmita-Dey** [comment]
@AliReza1083 The footer design is broken. I can't merge it in this way. Also, you haven't mentioned the issue no?


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

**Comment by AliReza1083** [comment]
Ok, let me do it again.

**Comment by Susmita-Dey** [comment]
@AliReza1083
What's the issue number?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by AliReza1083** [comment]
is it fixed?
I think right now the navbar is working fine as I checked the website.

**Comment by AliReza1083** [comment]
I don't see any issue.

**Comment by AliReza1083** [comment]
I just removed the extra lines.

**Comment by Susmita-Dey** [comment]
@AliReza1083 Have you created issues before this PR?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by AliReza1083** [comment]
No, I didn't

**Comment by AliReza1083** [comment]
Don't accept this PR. hahaha

Please assign me to fix that service layout issues.

**Comment by Susmita-Dey** [comment]
@AliReza1083 Sorry I can't merge your PR then. Closing this.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

**Comment by Susmita-Dey** [comment]
> Don't accept this PR. hahaha
> 
> Please assign me to fix that service layout issues.

Create an issue on your own with proper screenshot and changes you wanna make.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Tags:** Not reusable

**Pull request closed without merging**
