### PR TITLE
Pre-Loader has been added and Animation on Scrolling has been added

### PR DESCRIPTION
**Pull request by Anubhavgupta14**
Pre-Loader has been added and Animation on Scrolling has been added. #422 #423 
Pre-Loader Demo:-
Spin-Preloader-1
Animation Demo:-

https://user-images.githubusercontent.com/97956667/191355732-540465aa-b6a7-40d5-8a0e-fab80edc3c3b.mp4

@myhacktech @Susmita-Dey Please Review the PR.
Issue Solved #422 #423

### CODE REVIEW

**Comment by Susmita-Dey** [comment]
@Anubhavgupta14 Can you kindly make seperate PRs for seperate issues? 
If yes, then kindly comment and close this one.

**Comment by Susmita-Dey** [comment]
@Anubhavgupta14 According to deploy preview, there's no scrollbar. Fix it.

**Comment by Anubhavgupta14** [comment]
@Susmita-Dey Ok I will Make seperate PR for both issues.
Can you please share me the Screenshot where scroll bar is not present ?

**Comment by myhacktech** [comment]
as i can see preloader has been added @Susmita-Dey ...,
@Anubhavgupta14 if u wish u can make  separate prs for all loaders

**Comment by Anubhavgupta14** [comment]
@myhacktech OK sir I will make 2 PR for Both issues #422 and #423

**Pull request closed without merging**
