### PR TITLE
Enhanced the FAQ Section

### PR DESCRIPTION
**Pull request by Shivam-Katare**
Issue: #434 

### Preview

https://user-images.githubusercontent.com/91705825/191883502-09e98002-a3ca-47b7-a196-1aaad3f584e9.mp4

### CODE REVIEW

**Review by myhacktech — APPROVED** [review]
lgtm @Susmita-Dey

**Comment by Susmita-Dey** [comment]
@Shivam-Katare Fix merge conflicts

**Comment by Shivam-Katare** [comment]
> @Shivam-Katare Fix merge conflicts

Conflicts Resolved

**Comment by Susmita-Dey** [comment]
@Shivam-Katare Check the deploy preview once. Many things got changed which shouldn't be

**Comment by Susmita-Dey** [comment]
@Shivam-Katare Your PR has broken changes. I can't merge it in this way. Kindly check the deploy preview; many thinga have vanished.

**Comment by Shivam-Katare** [comment]
> @Shivam-Katare Your PR has broken changes. I can't merge it in this way. Kindly check the deploy preview; many things have vanished.

Yes! @Susmita-Dey  I checked it and resolved everything. You can check it now and merge it.

**Comment by Susmita-Dey** [comment]
@Shivam-Katare Where are these two FAQs in your PR?

It's in the website. Add them here too in your PR.

**Comment by Shivam-Katare** [comment]
> @Shivam-Katare Where are these two FAQs in your PR? (the last 2)
> 
> image
> 
> It's in the website. Add them here too in your PR.

@Susmita-Dey I  Added the rest of the FAQs.

Screenshot (39)

**Comment by Susmita-Dey** [comment]
LGTM

**Pull request merged**
