### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Eknoor02**
Added animations on the about section
Transitions added to the all the elements of the laughter page
Signed-off-by: Eknoor Singh <65605024+Eknoor02@users.noreply.github.com>
Issue #466  Issue #467

### CODE REVIEW

**Comment by myhacktech** [comment]
attach screenshot to explain

**Comment by Eknoor02** [comment]
Screenshot (201)
Area marked with the blue has been animated

**Review by myhacktech — APPROVED** [review]
lgtm @Susmita-Dey

**Comment by Susmita-Dey** [comment]
@Eknoor02 fix merge conflicts and pull recent changes in the website

**Comment by Eknoor02** [comment]
Conflics merged.

**Comment by Eknoor02** [comment]
All Conflicts have been merged.Kindly review this.

**Comment by Susmita-Dey** [comment]
@Eknoor02 Your changes are not reflected in the deploy preview link and also Standup section is duplicated. Check and correct it and then attach a video to show your changes

**Comment by Eknoor02** [comment]
I cannot figure out why the deploy preview is showing as such.I have reviewed the code and there are not as such flaws in it.

**Pull request closed without merging**
