### PR TITLE
Modified the responsive navbar

### LINKED ISSUE #576: [FEATURE] Make the mobile navbar come from right side
### Description

The responsive navbar i.e. the navbar for mobile screens comes from left side although the hamburger is on the right side. I want to change the modify the code so that it comes from right side. Kindly assign me this issue

### Screenshots

image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mohammadshaad**
Closes #576 

I have modified the navbar for smaller screens so that it appears from the right side and also I have added a close button on the navbar so when we click the icon the navbar closes eariler it was not there. Kindly review and merge the PR

## Screenshots
Screen Shot 2023-01-14 at 11 42 23 AM
Screen Shot 2023-01-14 at 11 42 36 AM

### CODE REVIEW

**Comment by mohammadshaad** [comment]
@Susmita-Dey kindly review and merge the PR

**Comment by Susmita-Dey** [comment]
@mohammadshaad I'm having exams now. Please wait for 10 more days

**Comment by mohammadshaad** [comment]
okay no problem. All the best for your exams

**Review by Susmita-Dey — APPROVED** [review]
LGTM. Great job

**Pull request merged**
