### PR TITLE
Corrected Hamburger Menu

### PR DESCRIPTION
**Pull request by SujalSamai**
The hamburger menu was overlapping earlier with the header. I have corrected it and added styling to it.
image

### CODE REVIEW

**Review by myhacktech — CHANGES_REQUESTED** [review]
Screenshot (664)
work on improving it

**Comment by Susmita-Dey** [comment]
@SujalSamai What's the issue number?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by SujalSamai** [comment]
> Screenshot (664) work on improving it

@myhacktech Sir that issue was not assigned to me, that responsiveness problem is due to the hero section, I was assigned only the hamburger menu, that's why I did not changed it. If you insist I would work on it.

**Comment by SujalSamai** [comment]
> @SujalSamai What's the issue number?
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** ❓ I have a question

Issue number #124

**Review by Susmita-Dey — APPROVED** [review]
LGTM.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Review by myhacktech — APPROVED** [review]

**Pull request merged**
