### PR TITLE
Issue #437 Fixed.

### PR DESCRIPTION
**Pull request by Stk-79**
Issue #437 

1. Made complete Laugh Therapy html code clean by giving proper spacing.
 
2. Changed the display for standup videos , & corrected the hover effect.

Before ->
[Untitled video - Screen Recording - 9_23_2022, 5_54_54 PM.webm](https://user-images.githubusercontent.com/102925712/191959832-5ab134d2-f346-440f-aef1-bcdc3fb56018.webm)

After Changes ->
[Untitled video - Screen Recording - 9_23_2022, 5_56_07 PM.webm](https://user-images.githubusercontent.com/102925712/191960224-e494dfcd-ebc4-47e1-a982-ac582c881b2b.webm)

### CODE REVIEW

**Comment by myhacktech** [comment]
mention issue

**Review by Susmita-Dey — APPROVED** [review]
Good job.

**Comment by Stk-79** [comment]
> 



> mention issue

Issue #437

**Comment by Stk-79** [comment]
> Good job.

Thanks Ma'am.

**Pull request merged**
