### PR TITLE
Fix Issue: #367 Improving the Responsiveness of the Yoga Therapy Page And Enhancing the design. 

### PR DESCRIPTION
**Pull request by SahilDahekar**
- Issue no. #367 
- Added new background to the landing part.
- Added Poppins font to the whole page.
- Added bullets to the benefits points about yoga.
- Added new color theme to the yoga-therapy page.
- Added responsiveness to the yoga-therapy page.
- Resolved side scrolling error.
- Resolved yoga images compressing issue.

Screenshot 2022-09-17 005734
Screenshot 2022-09-17 005758
Screenshot 2022-09-17 005817
Screenshot 2022-09-17 005914
Screenshot 2022-09-17 005936
Screenshot 2022-09-17 005948
Screenshot 2022-09-17 010006

### CODE REVIEW

**Review by Susmita-Dey — APPROVED** [review]
That's a great job

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome&nbsp; | &nbsp;**Tags:** Efficient

**Review by myhacktech — APPROVED** [review]

**Review by Susmita-Dey — CHANGES_REQUESTED** [review]
@SahilDahekar Pull the recent changes in the website

**Comment by Susmita-Dey** [comment]
@SahilDahekar Pull once again

**Review by Susmita-Dey — APPROVED** [review]
Good job

**Pull request merged**
