### PR TITLE
made the audiobooks open in new tab

### PR DESCRIPTION
**Pull request by Vanshiii203**
issue #402 

https://user-images.githubusercontent.com/94471189/190847213-98a8e8e3-8ba5-402f-8f37-e249742b5f29.mp4

### CODE REVIEW

**Review by myhacktech — APPROVED** [review]

**Comment by myhacktech** [comment]
great

**Comment by myhacktech** [comment]
LGTM @Susmita-Dey

**Comment by Susmita-Dey** [comment]
@Vanshiii203 Pull the latest changes

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by Vanshiii203** [comment]
@Susmita-Dey I have pulled the latest changes

**Pull request merged**
