### PR TITLE
Made Revealable Footer, new PR

### PR DESCRIPTION
**Pull request by MridulTi**
Solves Issue #347 
Earlier, when I made a PR for Footer Revealable there were many merge conflicts which is why I created this new PR so that the earlier issue can be resolved. This time around I made Footer Revealable for all pages except for index.html as it tends to create problems with a loading animation.
Earlier Footer:-
https://user-images.githubusercontent.com/92802892/187162527-a94e1238-ea31-44b6-935f-72ee77779e7b.png
The Footer was Static earlier

### CODE REVIEW

**Comment by Susmita-Dey** [comment]
@MridulTi It's a draft PR also your chanegs are not reflected in the deploy preview

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

**Comment by MridulTi** [comment]
The changes are reflected in the deploy preview its just on the other pages and not the main page because of the loading effect as I explained and the reason of it being a draft PR is that it contains one more commit for another issue, so I am waiting until that one gets merged just to make sure no conflict happens

**Comment by Susmita-Dey** [comment]
@MridulTi Stop working on it. I don't think that it would look good in a professional website.

**Comment by MridulTi** [comment]
> 

Ok then I will delete this PR

**Pull request closed without merging**
