### PR TITLE
made font-size, font family of all headings on home page similar

### PR DESCRIPTION
**Pull request by Vanshiii203**
issue #405
before-
Screenshot (399)
after-
https://user-images.githubusercontent.com/94471189/190895195-ad312b2e-30f2-413a-bbce-14a2e5004fbe.mp4

### CODE REVIEW

**Comment by myhacktech** [comment]
explain with screenshot

**Comment by Vanshiii203** [comment]
> explain with screenshot
@myhacktech 
I have Attached the screenshots

**Review by myhacktech — APPROVED** [review]
lgtm @Susmita-Dey

**Review by Susmita-Dey — APPROVED** [review]
LGTM

**Pull request merged**
