### PR TITLE
Added new font-family to let's connect

### PR DESCRIPTION
**Pull request by MohitNamdev22**
Issue #331 
I've changed the font family of the Let's Connect button.
image

### CODE REVIEW

**Review by Susmita-Dey — CHANGES_REQUESTED** [review]
Use **`Roboto Slab`** or **`ubuntu`** font. **Montserrat** doesn't makes any difference from the existing one.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by MohitNamdev22** [comment]
Okay @Susmita-Dey

**Comment by MohitNamdev22** [comment]
@Susmita-Dey Made the required changes 👍

**Review by Susmita-Dey — APPROVED** [review]
LGTM.

**Pull request merged**
