### PR TITLE
Added Footer to therapy pages

### PR DESCRIPTION
**Pull request by Surya8991**
Issue no #189 [SSOC 2022 participant]
Added Footer to therapy pages
image
image
image

### CODE REVIEW

**Review by myhacktech — APPROVED** [review]

**Comment by Surya8991** [comment]
@myhacktech can u close this pull req.

**Comment by myhacktech** [comment]
> @myhacktech can u close this pull req.

ok

**Comment by Surya8991** [comment]
Is it merged with project @myhacktech

**Comment by myhacktech** [comment]
> Is it merged with project @myhacktech

no,u asked to close the PR,thats why i closed

**Comment by Surya8991** [comment]
I thought it was merged

**Comment by myhacktech** [comment]
> > Is it merged with project @myhacktech
> 
> no,u asked to close the PR,thats why i closed



> I thought it was merged

@Susmita-Dey to be merged

**Comment by Surya8991** [comment]
Ok

**Comment by myhacktech** [comment]
> Is it merged with project @myhacktech

hope u did not made any changes after i closed this?

**Comment by Surya8991** [comment]
> > Is it merged with project @myhacktech
> 
> hope u did not made any changes after i closed this?

no

**Comment by Surya8991** [comment]
I was about do pull for another issue but didn't do

**Comment by myhacktech** [comment]
> I was about do pull for another issue but didn't do

ok then restore changes u have done for this PR,otherwise what u chaged after close of the PR,will also be merged unecessarily

**Comment by Surya8991** [comment]
how to do?

**Comment by Surya8991** [comment]
I didn't do any pull req today but it shows I did & I didn't make any changes to home button part.

**Comment by myhacktech** [comment]
> I didn't do any pull req today but it shows I did & I didn't make any changes to home button part.
https://deploy-preview-202--sukoon-stress-free.netlify.app/ chk this preview,if it has  same changes that u did...

**Comment by Surya8991** [comment]
yes the pull req is crt

**Comment by myhacktech** [comment]
> yes the pull req is correct

ok @Susmita-Dey u may merge this

**Comment by Susmita-Dey** [comment]
@Surya8991 Your branch has merge conflicts. Kindly fix them.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by Surya8991** [comment]
how to do it ?

**Comment by Surya8991** [comment]
what changes?

**Pull request merged**
