### PR TITLE
Improved the testimonial Section

### PR DESCRIPTION
**Pull request by Shivam-Katare**
issue #204 

image

### CODE REVIEW

**Review by Susmita-Dey — CHANGES_REQUESTED** [review]
Changes you need to make:
- Resolve merge conflicts
- Keep the text **"Testimonials"**
- You can improve the section something similar to this [template](https://nicepage.com/templates/preview/customer-feedbacks-347164?device=desktop)



__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by Shivam-Katare** [comment]
> Changes you need to make:
> 
> * Resolve merge conflicts
> * Keep the text **"Testimonials"**
> * You can improve the section something similar to this [template](https://nicepage.com/templates/preview/customer-feedbacks-347164?device=desktop)
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** 🛠️ This code needs a fix

Okay @Susmita-Dey I will resolve the merge conflict and improve the template.

**Comment by Susmita-Dey** [comment]
@Shivam-Katare Any updates? 

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by Shivam-Katare** [comment]
Sorry for the delay @Susmita-Dey My exams are going on that's why I wasn't able to complete. But, I will complete it today.

**Comment by Shivam-Katare** [comment]
Hey @Susmita-Dey, I update the **Testimonial Section.** You can check that now. Let me know if it needs any more changes.

# Preview

https://user-images.githubusercontent.com/91705825/187062775-5a163a72-3f0a-4ab9-b4e8-46ecb3bee599.mp4

**Pull request closed without merging**
