### PR TITLE
Sticky navbar

### PR DESCRIPTION
**Pull request by ShivanshAr97**
Fixes issue #227 

I have made the navbar sticky 

**Screenshot**
image

### CODE REVIEW

**Comment by myhacktech** [comment]
there is some glitch between homepage and navbar ,when u scroll down right from top, @ShivanshAr97

**Comment by ShivanshAr97** [comment]
@myhacktech the bug has been resolved.
Please see the issue once again.

**Comment by myhacktech** [comment]
> @myhacktech the bug has been resolved. Please see the issue once again.

good

**Review by myhacktech — APPROVED** [review]

**Comment by Susmita-Dey** [comment]
@ShivanshAr97 Fix the merge conflicts

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

**Review by Susmita-Dey — CHANGES_REQUESTED** [review]
@ShivanshAr97 Things aren't looking good in this way. 
As you can see:
image

Can you fix it? Or I guess this feature isn't needed now as there's already top to bottom button.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by ShivanshAr97** [comment]
> @ShivanshAr97 Things aren't looking good in this way. As you can see: image
> 
> Can you fix it? Or I guess this feature isn't needed now as there's already top to bottom button.
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** 🛠️ This code needs a fix

Wait let me see. I had done better. But some error occured while merging conflicts maybe😭. Let me correct again

image
Look there was a background to it when navbar is scroll below a certain point

**Comment by Susmita-Dey** [comment]
@ShivanshAr97 Your PR don't have any merge conflicts currently. Fix that and then I'll merge it.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

**Comment by ShivanshAr97** [comment]
> @ShivanshAr97 Your PR don't have any merge conflicts currently. Fix that and then I'll merge it.
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** 🛠️ This code needs a fix  |  **Tags:** Not reusable

Done
I have added the loader as well again

**Comment by Susmita-Dey** [comment]
@ShivanshAr97 merge conflicts again

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

**Comment by ShivanshAr97** [comment]
> @ShivanshAr97 merge conflicts again
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** 🛠️ This code needs a fix  |  **Tags:** Not reusable

Done

**Review by Susmita-Dey — APPROVED** [review]
LGTM.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Pull request merged**
