### PR TITLE
Fix Issue: #147 - Making the navbar on Audio page responsive

### PR DESCRIPTION
**Pull request by SahilDahekar**
- Added responsiveness to navbar.
- Added smooth scroll and hamburger menu with toggle functionality with ("x") svg.
Screenshot 2022-08-09 222014
Screenshot 2022-08-09 222035

### CODE REVIEW

**Comment by siddhi-244** [comment]
> * Added responsiveness to navbar.
> * Added smooth scroll and hamburger menu with toggle functionality with ("x") svg.
>   Screenshot 2022-08-09 222014
>   Screenshot 2022-08-09 222035

Can uh link the issue ?

**Review by myhacktech — APPROVED** [review]

**Comment by myhacktech** [comment]
@Susmita-Dey chk if its properly done

**Comment by myhacktech** [comment]
> * Added responsiveness to navbar.
> * Added smooth scroll and hamburger menu with toggle functionality with ("x") svg.
>   Screenshot 2022-08-09 222014
>   Screenshot 2022-08-09 222035

and yes,plz mention issue

**Comment by SahilDahekar** [comment]
> > * Added responsiveness to navbar.
> > * Added smooth scroll and hamburger menu with toggle functionality with ("x") svg.
> >   Screenshot 2022-08-09 222014
> >   Screenshot 2022-08-09 222035
> 
> Can uh link the issue ?

As mentioned in the title its issue no: #147

**Comment by SahilDahekar** [comment]
Hey can u merge the PR, I don't it has any issues.

**Review by Susmita-Dey — APPROVED** [review]
LGTM. 

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Comment by Susmita-Dey** [comment]
@SahilDahekar Your brach has merge conflicts. Kindly solve them other I can't merge your PR.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

**Comment by SahilDahekar** [comment]
Hey I just fixed the merge conflicts now you can merge my PR

**Review by siddhi-244 — APPROVED** [review]
LGTM

**Comment by Susmita-Dey** [comment]
@SahilDahekar fix merge conflicts

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

**Comment by SahilDahekar** [comment]
okay i'll fix it asap

**Comment by myhacktech** [comment]
LGTM @Susmita-Dey

**Pull request merged**
