### PR TITLE
feat: add welcome action

### LINKED ISSUE #553: feat: github action for greeting FTCs
### Description

**What do you think of adding a GitHub action for greeting the first-time contributors on the project!?**

It seems more engaging and encouraging to the new contributors, and to the ones who are getting started with open-source!! 🙂

### Screenshots

Some thing like this! 

image

### Additional information

I would love to work on this issue!

### PR DESCRIPTION
**Pull request by kumarsonsoff3**
## Changes proposed
- Add GitHub action for First-time Contributors.

## Fixes issue
closes #553

### CODE REVIEW

**Comment by kumarsonsoff3** [comment]
Exactly this is how these messages will appear for the first time contributors. 

## For First PR
image
## For First issue
image

**Comment by kumarsonsoff3** [comment]
Hey @Susmita-Dey, it has been a long time, is there something I could help you with in reviewing & merging this PR.

**Review by Susmita-Dey — APPROVED** [review]
LGTM!! Thanks for your contribution. Kindly join our [discord](https://discord.gg/g7FmxB9uZp) as we're thinking to upgrade the project and rebuild it.

**Comment by kumarsonsoff3** [comment]
Sure, joining inn. Would love to help where needed!! :)

**Pull request merged**
