### PR TITLE
Added signup page.

### PR DESCRIPTION
**Pull request by 09khu**
issue link :- https://github.com/Susmita-Dey/Sukoon/issues/122
image

### CODE REVIEW

**Review by Susmita-Dey — APPROVED** [review]
LGTM. Merging to main.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Comment by nawed2611** [comment]
Hey, thanks for making a PR!

Just a note - 
- [ ] Can you centre-align the `Sign-Up` text displayed on the form
- [ ] Can you make the `Sign-Up` button of lesser width

This [resource](https://css-tricks.com/a-complete-guide-to-links-and-buttons/#:~:text=A%20good%20rule%20is%20to,default%2C%20will%20submit%20that%20form.) might help for you!


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by nawed2611** [comment]
Ah! This looks merged maybe we can do that for another issue!

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Tags:** Reusable

**Comment by Susmita-Dey** [comment]
@nawed2611 Let's leave these small issues for other contributors to point out and help other contributors to contribute to this project. We have to keep in mind that we have 128+ contributors in this project. We have to give a chance to everyone if possible.

**Comment by nawed2611** [comment]
Sounds good!

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Tags:** Efficient

**Pull request merged**
