### PR TITLE
Audio Therapy Page UI Improved Carousal has been added

### PR DESCRIPTION
**Pull request by Anubhavgupta14**
Audio Therapy Page UI Improved Carousal has been added

### CODE REVIEW

**Comment by Anubhavgupta14** [comment]
g
Screenshot 2022-08-09 002736

**Comment by Anubhavgupta14** [comment]
@Susmita-Dey Please Review the PR

**Review by Susmita-Dey — COMMENTED** [review]
@Anubhavgupta14 What's the issue number? Also, the site doesn't look good after your changes.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by Anubhavgupta14** [comment]
https://github.com/Susmita-Dey/Sukoon/issues/143
#143 is my Issue number.

**Comment by Anubhavgupta14** [comment]
> 

I have attached the screenshot for what I have changed.

**Comment by Susmita-Dey** [comment]
@Anubhavgupta14 The issue was not assigned to you. I can't merge it. Sorry

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

**Pull request closed without merging**
