### PR TITLE
Enhanced UI of About Us page  issue#170

### PR DESCRIPTION
**Pull request by 29Aastha**
https://user-images.githubusercontent.com/101136877/184104624-b2b509f6-6bb3-4f7c-9fd8-4baeb606c66c.mp4

- Enhanced the UI of the About Us page
- added hover effect

### CODE REVIEW

**Review by Susmita-Dey — CHANGES_REQUESTED** [review]
Can you remove the bubbles or make the bubbles smaller in size?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

**Comment by myhacktech** [comment]
> About.Us.mp4 
> * Enhanced the UI of the About Us page
> * added hover effect

@29Aastha if u have made the changes ,then share screnshot or video for the sam,then we'll approve this

**Comment by 29Aastha** [comment]
> > About.Us.mp4
> > 
> > * Enhanced the UI of the About Us page
> > * added hover effect
> 
> @29Aastha if u have made the changes ,then share screnshot or video for the sam,then we'll approve this



https://user-images.githubusercontent.com/101136877/184473371-33e656bb-5d69-42d0-9aca-84264d1e16b8.mp4

I have reduced the size of bubbles

**Comment by Susmita-Dey** [comment]
@29Aastha Your branch has merge conflicts. Kindly fix them.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Pull request merged**
