### PR TITLE
Changed Styling of Services Section

### PR DESCRIPTION
**Pull request by SujalSamai**
Changed the styling of the cards of Service Section using Flexbox.
Decreased code lines and made the section responsive.
Also changed the images of the cards to make them look similar to each other.
Note: The earlier PR had code in different branch but as the maintainer insisted I'm raising the PR from the main branch
image

### CODE REVIEW

**Review by myhacktech — APPROVED** [review]

**Comment by myhacktech** [comment]
good work

**Comment by Susmita-Dey** [comment]
@SujalSamai issue no?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by myhacktech** [comment]
@SujalSamai mention issue with #?

**Comment by SujalSamai** [comment]
> @SujalSamai issue no?
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** ❓ I have a question

Issue no. #55 It is present in closed issue section

**Pull request merged**
