### PR TITLE
Service Section

### PR DESCRIPTION
**Pull request by AliReza1083**
I've fixed the Issue.
It's now responsive.
992 px > 3 Columns
768 px > 2 columns
576 px < 1 column

Also, I added a new hover effect on class .responsive.

### CODE REVIEW

**Comment by Susmita-Dey** [comment]
@AliReza1083 Your branch has merge conflicts. Kindly fix them.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

**Comment by AliReza1083** [comment]
@Susmita-Dey 
is it fixed?

**Comment by Susmita-Dey** [comment]
> @Susmita-Dey is it fixed?

Yes

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by AliReza1083** [comment]
will it be acceptable?

**Review by Susmita-Dey — APPROVED** [review]
LGTM.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Comment by Susmita-Dey** [comment]
@AliReza1083 Issue no? 
I can't give you points without this

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by AliReza1083** [comment]
Sorry, it's my first time collaborating here, and I don't know what do you mean with issue no?

**Comment by Susmita-Dey** [comment]
@AliReza1083  Go to the issue assigned to you to make this PR. Link it here in comment.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Tags:** Reusable

**Comment by AliReza1083** [comment]
Issue #250

**Pull request merged**
