### PR TITLE
Footer added

### PR DESCRIPTION
**Pull request by con-artist**
PR for issue #225
image
image
image

All services page now have the footer added to them
Please mege

### CODE REVIEW

**Comment by myhacktech** [comment]
great

**Review by myhacktech — APPROVED** [review]

**Comment by myhacktech** [comment]
LGTM @Susmita-Dey

**Comment by Susmita-Dey** [comment]
@con-artist Your branch has merge comflicts. Kindly fix them.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

**Comment by con-artist** [comment]
@Susmita-Dey  I am resolved the conflicts

**Comment by Susmita-Dey** [comment]
@con-artist Conflicts again.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by con-artist** [comment]
@Susmita-Dey  Fixed conflicts please merge

**Comment by Susmita-Dey** [comment]
@con-artist Sorry again but merge conflicts again. This is the last time fix it and tag me on discord. I'll merge it immediately

**Review by Susmita-Dey — APPROVED** [review]
Great job! LGTM.

**Comment by con-artist** [comment]
@Susmita-Dey  merge this PR please. 😧

**Comment by Susmita-Dey** [comment]
@con-artist merging

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome

**Pull request merged**
